import { cwd, exists, readFile, writeFile, join } from '../utils/fs.js'
import { intro, outro, log } from '../utils/ui.js'
import { requireConfig } from '../core/config.js'
import { printCommandFooter } from '../core/command-help.js'
import {
  buildCodexAdapterContext,
  renderAdapterMarkdown,
  renderKaddoBlock,
  detectAgentsState,
  injectKaddoBlock,
  ADAPTERS,
  findAdapter,
  buildAdapterStatuses,
  buildSharedFileStatuses,
} from '../core/codex-adapter.js'

type AdapterOpts = { force?: boolean; dryRun?: boolean; inject?: boolean }

const ADAPTER_LIST = ADAPTERS.map((a) => a.id).join(', ')

/**
 * `kaddo adapters install <adapter>` (alias `kaddo export <adapter>`) — generate the adapter
 * projection (AGENTS.md / CLAUDE.md) from Kaddo knowledge. All adapters support `--inject`.
 */
export function runAdaptersInstall(adapter: string, opts: AdapterOpts = {}): void {
  const dir = cwd()
  requireConfig(dir)

  const spec = findAdapter(adapter)
  if (!spec) {
    console.error(`Unknown adapter: "${adapter}". Available: ${ADAPTER_LIST}.`)
    process.exit(1)
    return
  }

  const ctx = buildCodexAdapterContext(dir)
  const rel = spec.file
  const full = join(dir, rel)
  const existed = exists(full)
  const existing = existed ? readFile(full) : null
  const cmd = `kaddo adapters install ${adapter}`

  // ── Inject mode (VS-065.2): add or update only the Kaddo block, preserving the rest. ──
  if (opts.inject && spec.supportsInject) {
    const state = detectAgentsState(existing)
    if (state === 'invalid_kaddo_block') {
      console.error(`Invalid Kaddo adapter block detected in ${rel}.`)
      console.error('Found one marker without its pair. Fix the file manually or use --force to overwrite.')
      console.error('Nothing changed.')
      process.exit(1)
      return
    }

    // Already a full Kaddo-generated file (header, no markers): injecting would duplicate the
    // guidance. --inject is for team-owned files; tell the user to regenerate with --force instead.
    if (state === 'generated_by_kaddo') {
      intro(`${cmd} --inject`)
      log.warn(`${rel} is already fully generated by Kaddo.`)
      log.info('Nothing injected to avoid duplicated Kaddo guidance.')
      log.info(`Use \`${cmd} --force\` to regenerate the full file.`)
      log.info(`\`--inject\` is for team-owned files: keep your own ${rel} and run \`${cmd} --inject\` to add the Kaddo block.`)
      outro('Nothing changed.')
      return
    }

    // No file yet: --inject behaves like a normal create (full projection).
    if (existing === null) {
      const content = renderAdapterMarkdown(ctx, spec.id)
      if (opts.dryRun) {
        console.log(`# ${rel} preview`, '')
        console.log(content)
        return
      }
      intro(`${cmd} --inject`)
      writeFile(full, content)
      log.success(`Created ${rel} for ${spec.label}.`)
      printCommandFooter('adapters install codex')
      outro(`${rel} ready.`)
      return
    }

    const merged = injectKaddoBlock(existing, ctx)
    if (opts.dryRun) {
      console.log(`# ${rel} preview (inject)`, '')
      console.log(merged.content)
      return
    }
    intro(`${cmd} --inject`)
    writeFile(full, merged.content)
    if (merged.status === 'updated') {
      log.success(`Updated existing Kaddo guidance block in ${rel}.`)
    } else {
      log.success(`Injected Kaddo guidance block into ${rel}.`)
    }
    log.info('Content outside the Kaddo markers was preserved.')
    printCommandFooter('adapters install codex')
    outro(`${rel} ready.`)
    return
  }

  const content = renderAdapterMarkdown(ctx, spec.id)

  // Preview only — write nothing.
  if (opts.dryRun) {
    console.log(`# ${rel} preview`, '')
    console.log(content)
    return
  }

  intro(cmd)

  if (existed && !opts.force) {
    log.warn(`${rel} already exists.`)
    if (spec.supportsInject) log.info('Use `--inject` to add or update only the Kaddo block,')
    log.info(`Use \`--force\` to overwrite, or \`--dry-run\` to preview.`)
    outro('Nothing changed.')
    return
  }

  writeFile(full, content)
  log.success(`${existed ? 'Overwrote' : 'Created'} ${rel} for ${spec.label}.`)
  log.info('Source: Kaddo project knowledge. Regenerate it instead of editing by hand.')
  printCommandFooter('adapters install codex')
  outro(`${rel} ready.`)
}

// Re-export for tests/consumers that want the raw block.
export { renderKaddoBlock }

/** `kaddo adapters list` — show the supported adapter catalog. Read-only, no project required. */
export function runAdaptersList(opts: { json?: boolean } = {}): void {
  if (opts.json) {
    console.log(JSON.stringify({ adapters: ADAPTERS.map((a) => ({ id: a.id, label: a.label, file: a.file, supports_inject: a.supportsInject })) }, null, 2))
    return
  }
  const pad = Math.max(...ADAPTERS.map((a) => a.id.length))
  console.log('Available adapters:\n')
  for (const a of ADAPTERS) {
    console.log(`  ${a.id.padEnd(pad)}  ${a.file.padEnd(10)} ${a.supportsInject ? 'Supports --inject' : ''}`.trimEnd())
  }
  console.log('\nInstall one with:\n  kaddo adapters install <adapter>')
  console.log('\nPreview with:\n  kaddo adapters install <adapter> --dry-run')
}

/** `kaddo adapters status` — inspect each adapter's target file state. Read-only. */
export function runAdaptersStatus(opts: { json?: boolean } = {}): void {
  const dir = cwd()
  requireConfig(dir)

  const statuses = buildAdapterStatuses(dir)

  if (opts.json) {
    console.log(JSON.stringify({
      adapters: statuses.map((s) => ({
        id: s.id,
        label: s.label,
        file: s.file,
        state: s.state,
        origin_adapter: s.originAdapter,
        supports_inject: s.supportsInject,
        recommended_action: s.recommendedAction,
      })),
      shared_files: buildSharedFileStatuses(statuses).map((f) => ({
        file: f.file,
        adapters: f.adapters,
        state: f.state,
        origin_adapter: f.originAdapter,
      })),
    }, null, 2))
    return
  }

  const idPad = Math.max(...statuses.map((s) => s.id.length))
  console.log('Adapter status:\n')
  for (const s of statuses) {
    const origin = s.originAdapter && s.originAdapter !== s.id ? ` by ${s.originAdapter}` : ''
    console.log(`  ${s.id.padEnd(idPad)}  ${s.file.padEnd(10)} ${s.state}${origin}`)
  }

  const actionable = statuses.filter((s) => s.state !== 'injected' && s.state !== 'full-generated')
  if (actionable.length > 0) {
    console.log('\nRecommended actions:\n')
    for (const s of actionable) console.log(`  ${s.id}:\n    ${s.recommendedAction}`)
  } else {
    console.log('\nAll adapters are installed or up to date.')
  }
}
