import { cwd, exists, readFile, writeFile, join } from '../utils/fs.js'
import { intro, outro, log } from '../utils/ui.js'
import { requireConfig } from '../core/config.js'
import { printCommandFooter } from '../core/command-help.js'
import {
  buildCodexAdapterContext,
  renderAdapterMarkdown,
  renderKaddoBlock,
  detectAgentsState,
  injectKaddoBlock,
  type AdapterTarget,
} from '../core/codex-adapter.js'

type AdapterOpts = { force?: boolean; dryRun?: boolean; inject?: boolean }

type TargetSpec = { target: AdapterTarget; file: string; label: string; supportsInject: boolean }
const TARGETS: Record<string, TargetSpec> = {
  codex: { target: 'codex', file: 'AGENTS.md', label: 'Codex', supportsInject: true },
  claude: { target: 'claude', file: 'CLAUDE.md', label: 'Claude Code', supportsInject: true },
  opencode: { target: 'opencode', file: 'AGENTS.md', label: 'OpenCode', supportsInject: true },
  antigravity: { target: 'antigravity', file: 'AGENTS.md', label: 'Antigravity', supportsInject: true },
}

/**
 * `kaddo adapters install <codex|claude>` (alias `kaddo export <adapter>`) — generate the adapter
 * projection (AGENTS.md / CLAUDE.md) from Kaddo knowledge. Codex also supports `--inject` (VS-065.2).
 */
export function runAdaptersInstall(adapter: string, opts: AdapterOpts = {}): void {
  const dir = cwd()
  requireConfig(dir)

  const spec = TARGETS[adapter]
  if (!spec) {
    console.error(`Unknown adapter: "${adapter}". Available: ${Object.keys(TARGETS).join(', ')}.`)
    process.exit(1)
    return
  }

  const ctx = buildCodexAdapterContext(dir)
  const rel = spec.file
  const full = join(dir, rel)
  const existed = exists(full)
  const existing = existed ? readFile(full) : null
  const cmd = `kaddo adapters install ${adapter}`

  // ── Inject mode (VS-065.2): add or update only the Kaddo block, preserving the rest. ──
  if (opts.inject && spec.supportsInject) {
    const state = detectAgentsState(existing)
    if (state === 'invalid_kaddo_block') {
      console.error(`Invalid Kaddo adapter block detected in ${rel}.`)
      console.error('Found one marker without its pair. Fix the file manually or use --force to overwrite.')
      console.error('Nothing changed.')
      process.exit(1)
      return
    }

    // Already a full Kaddo-generated file (header, no markers): injecting would duplicate the
    // guidance. --inject is for team-owned files; tell the user to regenerate with --force instead.
    if (state === 'generated_by_kaddo') {
      intro(`${cmd} --inject`)
      log.warn(`${rel} is already fully generated by Kaddo.`)
      log.info('Nothing injected to avoid duplicated Kaddo guidance.')
      log.info(`Use \`${cmd} --force\` to regenerate the full file.`)
      log.info(`\`--inject\` is for team-owned files: keep your own ${rel} and run \`${cmd} --inject\` to add the Kaddo block.`)
      outro('Nothing changed.')
      return
    }

    // No file yet: --inject behaves like a normal create (full projection).
    if (existing === null) {
      const content = renderAdapterMarkdown(ctx, spec.target)
      if (opts.dryRun) {
        console.log(`# ${rel} preview`, '')
        console.log(content)
        return
      }
      intro(`${cmd} --inject`)
      writeFile(full, content)
      log.success(`Created ${rel} for ${spec.label}.`)
      printCommandFooter('adapters install codex')
      outro(`${rel} ready.`)
      return
    }

    const merged = injectKaddoBlock(existing, ctx)
    if (opts.dryRun) {
      console.log(`# ${rel} preview (inject)`, '')
      console.log(merged.content)
      return
    }
    intro(`${cmd} --inject`)
    writeFile(full, merged.content)
    if (merged.status === 'updated') {
      log.success(`Updated existing Kaddo guidance block in ${rel}.`)
    } else {
      log.success(`Injected Kaddo guidance block into ${rel}.`)
    }
    log.info('Content outside the Kaddo markers was preserved.')
    printCommandFooter('adapters install codex')
    outro(`${rel} ready.`)
    return
  }

  const content = renderAdapterMarkdown(ctx, spec.target)

  // Preview only — write nothing.
  if (opts.dryRun) {
    console.log(`# ${rel} preview`, '')
    console.log(content)
    return
  }

  intro(cmd)

  if (existed && !opts.force) {
    log.warn(`${rel} already exists.`)
    if (spec.supportsInject) log.info('Use `--inject` to add or update only the Kaddo block,')
    log.info(`Use \`--force\` to overwrite, or \`--dry-run\` to preview.`)
    outro('Nothing changed.')
    return
  }

  writeFile(full, content)
  log.success(`${existed ? 'Overwrote' : 'Created'} ${rel} for ${spec.label}.`)
  log.info('Source: Kaddo project knowledge. Regenerate it instead of editing by hand.')
  printCommandFooter('adapters install codex')
  outro(`${rel} ready.`)
}

// Re-export for tests/consumers that want the raw block.
export { renderKaddoBlock }
