// Knowledge Discovery Engine (VS knowledge-discovery-semantic-recognition).
//
// Recognizes project knowledge by meaning and metadata (front-matter `type`) rather than
// by file path or name. Discovery priority: front-matter type → Kaddo conventions → path.
// This lets Kaddo report what knowledge actually exists even when it was consolidated,
// split, moved or generated by agents.

import { exists, readDir, isFile, join } from '../utils/fs.js'
import { readArtifacts } from '../services/artifact-reader.js'

export type LayerName = 'Business' | 'Product' | 'Tech' | 'Delivery'

/** Per-layer knowledge maturity. */
export type LayerMaturity = 'Missing' | 'Placeholder' | 'Weak' | 'Consolidated' | 'Structured' | 'Partial' | 'Traceable'

export type LayerStatus = { layer: LayerName; status: LayerMaturity; detected: string[] }

const KNOWLEDGE = 'knowledge'

/** The consolidated single-file type for each layer (bootstrap output). */
const CONSOLIDATED_TYPE: Record<'Business' | 'Product' | 'Tech', string> = {
  Business: 'business',
  Product: 'product',
  Tech: 'codebase',
}

/** Specialized (structured) artifact types per layer — recognized by front-matter type. */
const STRUCTURED_TYPES: Record<LayerName, Set<string>> = {
  Business: new Set(['problem', 'users', 'value-proposition', 'business-rules', 'constraints', 'glossary']),
  Product: new Set(['product-brief', 'capabilities']),
  Tech: new Set([
    'current-state',
    'architecture-notes',
    'decision-candidates',
    'quality-attributes',
    'stack',
    'standards',
    'security',
    'git-strategy',
    'module-design',
    'adr',
    'decision',
  ]),
  Delivery: new Set([]),
}

/** Work-item kinds — a Delivery artifact is a Work Item when its type is one of these. */
export const WORK_ITEM_TYPES = new Set([
  'work-item',
  'feature',
  'bugfix',
  'hotfix',
  'spike',
])

/** Map a front-matter type to its layer (or null if unknown). */
export function layerForType(type: string): LayerName | null {
  if (!type) return null
  if (type === CONSOLIDATED_TYPE.Business || STRUCTURED_TYPES.Business.has(type)) return 'Business'
  if (type === CONSOLIDATED_TYPE.Product || STRUCTURED_TYPES.Product.has(type)) return 'Product'
  if (type === CONSOLIDATED_TYPE.Tech || STRUCTURED_TYPES.Tech.has(type) || type === 'knowledge')
    return 'Tech'
  if (type === 'roadmap' || WORK_ITEM_TYPES.has(type)) return 'Delivery'
  return null
}

/** Infer a layer from a knowledge/<layer>/ path when front matter is absent. */
function layerFromPath(filePath: string): LayerName | null {
  const p = filePath.replace(/\\/g, '/')
  if (p.includes(`/${KNOWLEDGE}/business/`)) return 'Business'
  if (p.includes(`/${KNOWLEDGE}/product/`)) return 'Product'
  if (p.includes(`/${KNOWLEDGE}/tech/`)) return 'Tech'
  if (p.includes(`/${KNOWLEDGE}/delivery/`)) return 'Delivery'
  return null
}

function basename(p: string): string {
  return p.replace(/\\/g, '/').split('/').pop() ?? p
}

type LayerAccumulator = {
  consolidated: boolean
  structured: boolean
  hasRoadmap: boolean
  hasWorkItem: boolean
  hasDecision: boolean
  detected: Set<string>
}

/**
 * Discover knowledge per layer, primarily by front-matter type, falling back to path. Pure
 * file reads — no interpretation, no LLM.
 */
export function discoverLayers(dir: string): LayerStatus[] {
  const acc: Record<LayerName, LayerAccumulator> = {
    Business: blank(),
    Product: blank(),
    Tech: blank(),
    Delivery: blank(),
  }

  const archDir = join(dir, KNOWLEDGE)
  const artifacts = exists(archDir) ? readArtifacts(archDir) : []

  for (const a of artifacts) {
    const type = a.type
    const layer = layerForType(type) ?? layerFromPath(a.filePath)
    if (!layer) continue
    const slot = acc[layer]
    slot.detected.add(basename(a.filePath))

    if (layer === 'Delivery') {
      if (type === 'roadmap' || basename(a.filePath) === 'roadmap.md') slot.hasRoadmap = true
      if (
        WORK_ITEM_TYPES.has(type) ||
        a.filePath.replace(/\\/g, '/').includes('/delivery/work-items/')
      ) {
        if (a.filePath.replace(/\\/g, '/').includes('/delivery/work-items/')) slot.hasWorkItem = true
      }
      continue
    }
    if (type === CONSOLIDATED_TYPE[layer as 'Business' | 'Product' | 'Tech']) slot.consolidated = true
    else if (STRUCTURED_TYPES[layer].has(type)) slot.structured = true
    else if (!type) {
      // typed-less file inside the layer folder counts as consolidated-level knowledge
      slot.consolidated = true
    }
    if (type === 'adr' || type === 'decision') slot.hasDecision = true
  }

  // Decisions can also be detected by their folder, even if untyped.
  if (existsDirWithMd(join(dir, KNOWLEDGE, 'tech', 'decisions'))) acc.Tech.structured = true

  return (['Business', 'Product', 'Tech', 'Delivery'] as LayerName[]).map((layer) => ({
    layer,
    status: statusFor(layer, acc[layer]),
    detected: [...acc[layer].detected].sort(),
  }))
}

function blank(): LayerAccumulator {
  return {
    consolidated: false,
    structured: false,
    hasRoadmap: false,
    hasWorkItem: false,
    hasDecision: false,
    detected: new Set(),
  }
}

function existsDirWithMd(d: string): boolean {
  if (!exists(d)) return false
  try {
    return readDir(d).some((e) => e.endsWith('.md') && isFile(join(d, e)))
  } catch {
    return false
  }
}

function statusFor(layer: LayerName, a: LayerAccumulator): LayerMaturity {
  if (layer === 'Delivery') {
    if (a.hasWorkItem) return 'Traceable'
    if (a.hasRoadmap) return 'Partial'
    return 'Missing'
  }
  if (a.structured) return 'Structured'
  if (a.consolidated) return 'Consolidated'
  return 'Missing'
}
