// Unified next-step recommendation (VS-073.2).
//
// A single deterministic source of truth for "what should I do next?". context, understand, explain
// and readiness all consume this so a project never gets two contradictory recommendations. Pure and
// read-only: no LLM, no git, no command execution, no knowledge edits. When in doubt it stays
// conservative and never recommends `create --from roadmap` with an empty roadmap.

import { exists, readFile, join } from '../utils/fs.js'
import { loadConfig } from './config.js'
import { analyzeKnowledgeArtifact } from './artifact-quality.js'
import { buildOpenQuestionsReport } from './open-questions.js'
import { discoverWorkItems } from '../services/knowledge-artifacts.js'
import { buildAdapterStatuses, buildCodexAdapterContext } from './codex-adapter.js'

export type RoadmapSignal = 'missing' | 'empty' | 'has-candidates'
export type WorkItemsSignal = 'none' | 'none-ready' | 'ready' | 'in-progress'

export type NextStepRecommendation = {
  id: string
  phase: string
  label: string
  command?: string
  agent?: string
  target?: string
  reason: string
  instructions?: string[]
}

/** Roadmap candidate signal (bullets/table rows outside an Open Questions section). */
export function roadmapSignal(dir: string): RoadmapSignal {
  const p = join(dir, 'knowledge/delivery/roadmap.md')
  if (!exists(p)) return 'missing'
  let md: string
  try {
    md = readFile(p)
  } catch {
    return 'missing'
  }
  const lines = md.replace(/^---[\s\S]*?---/m, '').split(/\r?\n/)
  let inOpenQuestions = false
  let candidates = 0
  for (const l of lines) {
    if (/^#{1,6}\s/.test(l)) inOpenQuestions = /open questions|preguntas abiertas/i.test(l)
    else if (!inOpenQuestions && /^\s*(?:[-*]\s+|\|)/.test(l)) candidates += 1
  }
  return candidates > 0 ? 'has-candidates' : 'empty'
}

export function workItemsSignal(dir: string): WorkItemsSignal {
  const wis = discoverWorkItems(dir)
  if (wis.length === 0) return 'none'
  if (wis.some((w) => w.lifecycle === 'in-progress')) return 'in-progress'
  if (wis.some((w) => w.lifecycle === 'ready')) return 'ready'
  return 'none-ready'
}

/** Adapters considered installed: injected files, or fully generated by that specific adapter. */
export function installedAdapters(dir: string): string[] {
  return buildAdapterStatuses(dir)
    .filter((s) =>
      s.state === 'injected' ||
      s.state === 'legacy-injected' ||
      (s.state === 'full-generated' && (s.originAdapter === s.id || s.originAdapter === null)),
    )
    .map((s) => s.id)
}

const B = 'knowledge/business/business.md'
const P = 'knowledge/product/product.md'
const CAP = 'knowledge/product/capabilities.md'
const CS = 'knowledge/tech/current-state.md'
const CB = 'knowledge/tech/codebase.md'

/**
 * Resolve the single next step for a project from its real state. The priority ladder is:
 * init → bootstrap → agents → skills → scan → context → understand → refine Business → Product →
 * Tech(current-state) → Tech(codebase) → blocking questions → roadmap → create → adapter → implement.
 */
export function resolveNextStep(dir: string, now: Date = new Date()): NextStepRecommendation {
  const config = loadConfig(dir)
  if (!config) {
    return { id: 'init', phase: 'Setup', label: 'Run `kaddo init` to initialize Kaddo.', command: 'kaddo init', reason: 'Kaddo is not initialized in this project.' }
  }
  const state = config.project.state

  const q = (rel: string) => analyzeKnowledgeArtifact(dir, rel)
  const qBusiness = q(B), qProduct = q(P), qCap = q(CAP), qCurrentState = q(CS), qCodebase = q(CB)

  // Baseline "exists" once bootstrap has created business + product (any quality).
  if (qBusiness === 'missing' || qProduct === 'missing') {
    return { id: 'bootstrap', phase: 'Setup', label: 'Run `kaddo bootstrap` to create the project knowledge baseline.', command: 'kaddo bootstrap', reason: 'The knowledge baseline is incomplete.' }
  }

  const ctx = buildCodexAdapterContext(dir)
  if (!ctx.hasAgents) {
    return { id: 'add-agents', phase: 'Setup', label: 'Run `kaddo add agents` to install the Kaddo agent prompt packs.', command: 'kaddo add agents', reason: 'No Kaddo agents are installed yet.' }
  }
  if (!ctx.hasSkills) {
    return { id: 'add-skills', phase: 'Setup', label: 'Run `kaddo add skills` to install reusable Kaddo skills.', command: 'kaddo add skills', reason: 'No Kaddo skills are installed yet.' }
  }

  if ((state === 'pre-ai' || state === 'legacy') && !exists(join(dir, '.kaddo', 'scan.json'))) {
    return { id: 'scan', phase: 'Discovery', label: 'Run `kaddo scan` to capture deterministic signals from the existing code.', command: 'kaddo scan', reason: 'No scan baseline exists for this existing project yet.' }
  }
  if (!exists(join(dir, '.kaddo', 'context-pack.md'))) {
    return { id: 'context', phase: 'Discovery', label: 'Run `kaddo context` to prepare the LLM context pack.', command: 'kaddo context', reason: 'No context pack has been generated yet.' }
  }
  if (!exists(join(dir, '.kaddo', 'understand.md'))) {
    return { id: 'understand', phase: 'Discovery', label: 'Run `kaddo understand` to summarize the project context.', command: 'kaddo understand', reason: 'No understand handoff has been generated yet.' }
  }

  // Knowledge refinement — keep the layer order Business → Product → Tech.
  const discovery = state === 'pre-ai' || state === 'legacy'
  const refine = (id: string, agent: string, target: string, quality: string, verb = 'complete'): NextStepRecommendation => ({
    id, phase: 'Knowledge Refinement', label: `Use ${agent} to ${verb} \`${target}\`.`, agent, target,
    reason: `${target} is ${quality === 'missing' ? 'missing' : 'still a bootstrap placeholder or too thin'}.`,
    instructions: [
      'The baseline file exists but does not yet hold real, project-specific knowledge.',
      `Use the ${agent} to replace the placeholders with real knowledge.`,
      'Do not write code.',
    ],
  })
  if (qBusiness !== 'useful') return refine('refine-business', 'business-agent', B, qBusiness)
  if (qProduct !== 'useful' || qCap !== 'useful') {
    // For existing projects, capabilities is a *discovery* of what the system already does (VS-074).
    if (qCap !== 'useful') {
      return refine('refine-product', 'capability-agent', CAP, qCap, discovery ? 'discover and document existing system capabilities in' : 'complete')
    }
    return refine('refine-product', 'capability-agent', P, qProduct)
  }
  if (qCurrentState !== 'useful') return refine('refine-current-state', 'architecture-agent', CS, qCurrentState)
  if (qCodebase !== 'useful') {
    const agent = ctx.agents.includes('codebase-agent') ? 'codebase-agent' : 'architecture-agent'
    return refine('refine-codebase', agent, CB, qCodebase)
  }

  // Foundational knowledge is useful — now decisions, roadmap and delivery.
  const oq = buildOpenQuestionsReport(dir, now)
  if (oq.summary.blocking_open > 0) {
    return { id: 'questions', phase: 'Knowledge Refinement', label: 'Run `kaddo questions` to see source locations and resolution guidance, then resolve, assume or defer the blocking open questions.', command: 'kaddo questions', reason: `${oq.summary.blocking_open} blocking open question(s) remain.` }
  }

  const roadmap = roadmapSignal(dir)
  if (roadmap !== 'has-candidates') {
    return { id: 'roadmap', phase: 'Planning', label: 'Use roadmap-agent to define roadmap candidates (`kaddo roadmap`).', command: 'kaddo roadmap', agent: 'roadmap-agent', target: 'knowledge/delivery/roadmap.md', reason: 'The roadmap has no candidates yet.' }
  }

  const wi = workItemsSignal(dir)
  if (wi === 'none' || wi === 'none-ready') {
    return { id: 'create-work-item', phase: 'Delivery Preparation', label: 'Run `kaddo create --from roadmap` to materialize the first Work Item.', command: 'kaddo create --from roadmap', reason: 'The roadmap has candidates but no Work Item is ready.' }
  }

  const adapters = installedAdapters(dir)
  if (adapters.length === 0) {
    return { id: 'install-adapter', phase: 'Active Delivery', label: 'Run `kaddo adapters list` and install the adapter for your preferred agent.', command: 'kaddo adapters list', reason: 'A Work Item is ready but no adapter is installed.' }
  }
  return { id: 'implement', phase: 'Active Delivery', label: 'Implement the ready Work Item and run `kaddo guard`.', reason: 'A Work Item is ready and an adapter is installed.' }
}
