// Pre-AI Onboarding Report (VS-072).
//
// Deterministic diagnosis of how ready an existing (pre-ai) project is to work with agents. Reads
// existing signals only — config, scan, understand, knowledge files, open-questions readiness,
// roadmap, Work Items and adapter status. Never runs other commands, never writes (the command layer
// writes the derived report under .kaddo/reports/), never edits knowledge, no git, no LLM.

import { exists, readFile, join } from '../utils/fs.js'
import { loadConfig } from './config.js'
import { buildOpenQuestionsReport } from './open-questions.js'
import { discoverWorkItems } from '../services/knowledge-artifacts.js'
import { buildAdapterStatuses } from './codex-adapter.js'

export type OnboardingStatus =
  | 'not-initialized'
  | 'not-applicable'
  | 'legacy-project'
  | 'initialized'
  | 'scanned'
  | 'knowledge-incomplete'
  | 'needs-decisions'
  | 'ready-for-roadmap'
  | 'ready-for-work-item'
  | 'ready-for-implementation'

export type Presence = 'present' | 'missing' | 'weak'
export type RoadmapSignal = 'missing' | 'empty' | 'has-candidates'
export type WorkItemsSignal = 'none' | 'none-ready' | 'ready' | 'in-progress'

export type OnboardingReport = {
  generated_at: string
  project_name: string
  project_type: string
  status: OnboardingStatus
  signals: {
    scan: 'available' | 'missing'
    understand: 'available' | 'missing'
    current_state: Presence
    codebase: Presence
    capabilities: Presence
    product: Presence
    business: Presence
    roadmap: RoadmapSignal
    work_items: WorkItemsSignal
    adapters: string[]
    blocking_open_questions: number
    assumed_questions: number
    resolved_questions: number
    deferred_questions: number
  }
  recommended_next_step: { label: string; command?: string }
}

const KNOWLEDGE_FILES: { key: 'current_state' | 'codebase' | 'capabilities' | 'product' | 'business'; path: string; label: string }[] = [
  { key: 'current_state', path: 'knowledge/tech/current-state.md', label: 'knowledge/tech/current-state.md' },
  { key: 'codebase', path: 'knowledge/tech/codebase.md', label: 'knowledge/tech/codebase.md' },
  { key: 'capabilities', path: 'knowledge/product/capabilities.md', label: 'knowledge/product/capabilities.md' },
  { key: 'product', path: 'knowledge/product/product.md', label: 'knowledge/product/product.md' },
  { key: 'business', path: 'knowledge/business/business.md', label: 'knowledge/business/business.md' },
]

/** Presence of a knowledge file: missing, weak (only frontmatter/headings) or present (real body). */
function knowledgePresence(dir: string, rel: string): Presence {
  const p = join(dir, rel)
  if (!exists(p)) return 'missing'
  let md: string
  try {
    md = readFile(p)
  } catch {
    return 'missing'
  }
  const body = md
    .replace(/^---[\s\S]*?---/m, '') // front matter
    .split(/\r?\n/)
    .filter((l) => !/^\s*#{1,6}\s/.test(l) && !/^\s*$/.test(l) && !/^\s*<!--/.test(l))
    .join(' ')
    .trim()
  return body.length >= 40 ? 'present' : 'weak'
}

function roadmapSignal(dir: string): RoadmapSignal {
  const p = join(dir, 'knowledge/delivery/roadmap.md')
  if (!exists(p)) return 'missing'
  let md: string
  try {
    md = readFile(p)
  } catch {
    return 'missing'
  }
  const stripped = md.replace(/^---[\s\S]*?---/m, '')
  // Candidates = list items / table rows outside an Open Questions section.
  const lines = stripped.split(/\r?\n/)
  let inOpenQuestions = false
  let candidates = 0
  for (const l of lines) {
    if (/^#{1,6}\s/.test(l)) inOpenQuestions = /open questions|preguntas abiertas/i.test(l)
    else if (!inOpenQuestions && /^\s*(?:[-*]\s+|\|)/.test(l)) candidates += 1
  }
  return candidates > 0 ? 'has-candidates' : 'empty'
}

function workItemsSignal(dir: string): WorkItemsSignal {
  const wis = discoverWorkItems(dir)
  if (wis.length === 0) return 'none'
  if (wis.some((w) => w.lifecycle === 'in-progress')) return 'in-progress'
  if (wis.some((w) => w.lifecycle === 'ready')) return 'ready'
  return 'none-ready'
}

/** Adapters considered "installed": injected files, or fully generated by that specific adapter. */
function installedAdapters(dir: string): string[] {
  return buildAdapterStatuses(dir)
    .filter((s) =>
      s.state === 'injected' ||
      s.state === 'legacy-injected' ||
      (s.state === 'full-generated' && (s.originAdapter === s.id || s.originAdapter === null)),
    )
    .map((s) => s.id)
}

/** Build the deterministic pre-AI onboarding report. */
export function buildOnboardingReport(dir: string, now: Date = new Date()): OnboardingReport {
  const config = loadConfig(dir)
  const ts = now.toISOString()

  const notReady = (status: OnboardingStatus, label: string, command?: string): OnboardingReport => ({
    generated_at: ts,
    project_name: config?.project.name ?? 'unknown',
    project_type: config?.project.state ?? 'unknown',
    status,
    signals: {
      scan: 'missing', understand: 'missing',
      current_state: 'missing', codebase: 'missing', capabilities: 'missing', product: 'missing', business: 'missing',
      roadmap: 'missing', work_items: 'none', adapters: [],
      blocking_open_questions: 0, assumed_questions: 0, resolved_questions: 0, deferred_questions: 0,
    },
    recommended_next_step: { label, ...(command ? { command } : {}) },
  })

  if (!config) return notReady('not-initialized', 'Run `kaddo init` to initialize Kaddo.', 'kaddo init')
  if (config.project.state === 'new') return notReady('not-applicable', 'This guide is optimized for pre-AI projects. Use the standard new-project Kaddo flow.')
  if (config.project.state === 'legacy') return notReady('legacy-project', 'Use the legacy project flow. The onboarding guide targets pre-AI projects.')

  // pre-ai: full diagnosis.
  const scan = exists(join(dir, '.kaddo', 'scan.json')) ? 'available' : 'missing'
  const understand = exists(join(dir, '.kaddo', 'understand.md')) ? 'available' : 'missing'
  const presence = Object.fromEntries(KNOWLEDGE_FILES.map((f) => [f.key, knowledgePresence(dir, f.path)])) as Record<typeof KNOWLEDGE_FILES[number]['key'], Presence>
  const roadmap = roadmapSignal(dir)
  const work_items = workItemsSignal(dir)
  const adapters = installedAdapters(dir)
  const oq = buildOpenQuestionsReport(dir, now)

  const signals = {
    scan, understand,
    current_state: presence.current_state, codebase: presence.codebase, capabilities: presence.capabilities,
    product: presence.product, business: presence.business,
    roadmap, work_items, adapters,
    blocking_open_questions: oq.summary.blocking_open,
    assumed_questions: oq.summary.resolution.assumed,
    resolved_questions: oq.summary.resolution.resolved,
    deferred_questions: oq.summary.resolution.deferred,
  } as OnboardingReport['signals']

  let status: OnboardingStatus
  let next: { label: string; command?: string }

  const firstWeak = KNOWLEDGE_FILES.find((f) => presence[f.key] !== 'present')

  if (scan === 'missing') {
    status = 'initialized'
    next = { label: 'Run `kaddo scan` to capture deterministic signals from the existing code.', command: 'kaddo scan' }
  } else if (understand === 'missing') {
    status = 'scanned'
    next = { label: 'Run `kaddo understand` to summarize the project context.', command: 'kaddo understand' }
  } else if (firstWeak) {
    status = 'knowledge-incomplete'
    next = { label: `Complete \`${firstWeak.label}\` (it is ${presence[firstWeak.key]}).` }
  } else if (oq.summary.blocking_open > 0) {
    status = 'needs-decisions'
    next = { label: 'Resolve, assume or defer the blocking open questions (`kaddo questions`).', command: 'kaddo questions' }
  } else if (roadmap !== 'has-candidates') {
    status = 'ready-for-roadmap'
    next = { label: 'Run `kaddo roadmap` to draft the roadmap from the current knowledge.', command: 'kaddo roadmap' }
  } else if (work_items === 'none' || work_items === 'none-ready') {
    status = 'ready-for-work-item'
    next = { label: 'Run `kaddo create --from roadmap` to materialize the first Work Item.', command: 'kaddo create --from roadmap' }
  } else {
    status = 'ready-for-implementation'
    next = adapters.length > 0
      ? { label: 'Implement the ready Work Item with an installed adapter, then run `kaddo guard`.' }
      : { label: 'Install an adapter, then implement the ready Work Item.', command: 'kaddo adapters list' }
  }

  return { generated_at: ts, project_name: config.project.name, project_type: config.project.state, status, signals, recommended_next_step: next }
}

export function serializeOnboardingJson(r: OnboardingReport): string {
  return JSON.stringify(r, null, 2) + '\n'
}

export function renderOnboardingMarkdown(r: OnboardingReport): string {
  const s = r.signals
  const L: string[] = []
  L.push('# Pre-AI Onboarding Report', '')
  L.push('## Summary', '')
  L.push(`- Project: ${r.project_name}`)
  L.push(`- Project type: ${r.project_type}`)
  L.push(`- Status: ${r.status}`)
  L.push('')
  if (r.status === 'not-initialized' || r.status === 'not-applicable' || r.status === 'legacy-project') {
    L.push('## Recommended Next Step', '', r.recommended_next_step.label, '')
    return L.join('\n')
  }
  L.push('## Signals', '')
  L.push(`- Scan: ${s.scan}`)
  L.push(`- Understand: ${s.understand}`)
  L.push(`- Current state: ${s.current_state}`)
  L.push(`- Codebase: ${s.codebase}`)
  L.push(`- Capabilities: ${s.capabilities}`)
  L.push(`- Product: ${s.product}`)
  L.push(`- Business: ${s.business}`)
  L.push(`- Roadmap: ${s.roadmap}`)
  L.push(`- Work Items: ${s.work_items}`)
  L.push(`- Adapters: ${s.adapters.length > 0 ? s.adapters.join(', ') + ' installed' : 'none installed'}`)
  L.push('')
  L.push('## Questions', '')
  L.push(`- Blocking open: ${s.blocking_open_questions}`)
  L.push(`- Assumed: ${s.assumed_questions}`)
  L.push(`- Resolved: ${s.resolved_questions}`)
  L.push(`- Deferred: ${s.deferred_questions}`)
  L.push('')
  L.push('## Recommended Next Step', '', r.recommended_next_step.label, '')
  return L.join('\n')
}
