// Project readiness (VS-072 / folded into explain by VS-072.1).
//
// Deterministic diagnosis of where a project sits in the Kaddo cycle and the single next step. Reads
// existing signals only — config, scan, understand, agents/skills, knowledge files, open-questions
// readiness, roadmap, Work Items and adapter status. Never runs other commands, never writes, never
// edits knowledge, no git, no LLM. Surfaced inside `kaddo explain`.

import { exists, readFile, join } from '../utils/fs.js'
import { loadConfig } from './config.js'
import { buildOpenQuestionsReport } from './open-questions.js'
import { discoverWorkItems } from '../services/knowledge-artifacts.js'
import { buildAdapterStatuses, buildCodexAdapterContext } from './codex-adapter.js'

export type ReadinessStatus =
  | 'not-initialized'
  | 'not-applicable'
  | 'legacy-project'
  | 'initialized'
  | 'scanned'
  | 'bootstrap-incomplete'
  | 'agents-missing'
  | 'skills-missing'
  | 'knowledge-incomplete'
  | 'needs-decisions'
  | 'ready-for-roadmap'
  | 'ready-for-work-item'
  | 'ready-for-implementation'

export type Presence = 'present' | 'missing' | 'weak'
export type RoadmapSignal = 'missing' | 'empty' | 'has-candidates'
export type WorkItemsSignal = 'none' | 'none-ready' | 'ready' | 'in-progress'

export type ReadinessReport = {
  project_name: string
  project_type: string
  overall: ReadinessStatus
  signals: {
    scan: 'available' | 'missing'
    understand: 'available' | 'missing'
    bootstrap_baseline: 'complete' | 'incomplete'
    agents: 'present' | 'missing'
    skills: 'present' | 'missing'
    current_state: Presence
    codebase: Presence
    capabilities: Presence
    product: Presence
    business: Presence
    roadmap: RoadmapSignal
    work_items: WorkItemsSignal
    adapters: string[]
    blocking_open_questions: number
    assumed_questions: number
    resolved_questions: number
    deferred_questions: number
  }
  recommended_next_step: { label: string; command?: string }
}

const KNOWLEDGE_FILES: { key: 'current_state' | 'codebase' | 'capabilities' | 'product' | 'business'; path: string; label: string }[] = [
  { key: 'current_state', path: 'knowledge/tech/current-state.md', label: 'knowledge/tech/current-state.md' },
  { key: 'codebase', path: 'knowledge/tech/codebase.md', label: 'knowledge/tech/codebase.md' },
  { key: 'capabilities', path: 'knowledge/product/capabilities.md', label: 'knowledge/product/capabilities.md' },
  { key: 'product', path: 'knowledge/product/product.md', label: 'knowledge/product/product.md' },
  { key: 'business', path: 'knowledge/business/business.md', label: 'knowledge/business/business.md' },
]

/** Presence of a knowledge file: missing, weak (only front matter/headings) or present (real body). */
export function knowledgePresence(dir: string, rel: string): Presence {
  const p = join(dir, rel)
  if (!exists(p)) return 'missing'
  let md: string
  try {
    md = readFile(p)
  } catch {
    return 'missing'
  }
  const body = md
    .replace(/^---[\s\S]*?---/m, '')
    .split(/\r?\n/)
    .filter((l) => !/^\s*#{1,6}\s/.test(l) && !/^\s*$/.test(l) && !/^\s*<!--/.test(l))
    .join(' ')
    .trim()
  return body.length >= 40 ? 'present' : 'weak'
}

function roadmapSignal(dir: string): RoadmapSignal {
  const p = join(dir, 'knowledge/delivery/roadmap.md')
  if (!exists(p)) return 'missing'
  let md: string
  try {
    md = readFile(p)
  } catch {
    return 'missing'
  }
  const lines = md.replace(/^---[\s\S]*?---/m, '').split(/\r?\n/)
  let inOpenQuestions = false
  let candidates = 0
  for (const l of lines) {
    if (/^#{1,6}\s/.test(l)) inOpenQuestions = /open questions|preguntas abiertas/i.test(l)
    else if (!inOpenQuestions && /^\s*(?:[-*]\s+|\|)/.test(l)) candidates += 1
  }
  return candidates > 0 ? 'has-candidates' : 'empty'
}

function workItemsSignal(dir: string): WorkItemsSignal {
  const wis = discoverWorkItems(dir)
  if (wis.length === 0) return 'none'
  if (wis.some((w) => w.lifecycle === 'in-progress')) return 'in-progress'
  if (wis.some((w) => w.lifecycle === 'ready')) return 'ready'
  return 'none-ready'
}

/** Adapters considered "installed": injected files, or fully generated by that specific adapter. */
function installedAdapters(dir: string): string[] {
  return buildAdapterStatuses(dir)
    .filter((s) =>
      s.state === 'injected' ||
      s.state === 'legacy-injected' ||
      (s.state === 'full-generated' && (s.originAdapter === s.id || s.originAdapter === null)),
    )
    .map((s) => s.id)
}

/** Build the deterministic project readiness diagnosis. */
export function buildReadinessReport(dir: string, now: Date = new Date()): ReadinessReport {
  const config = loadConfig(dir)

  const stub = (overall: ReadinessStatus, label: string, command?: string): ReadinessReport => ({
    project_name: config?.project.name ?? 'unknown',
    project_type: config?.project.state ?? 'unknown',
    overall,
    signals: {
      scan: 'missing', understand: 'missing', bootstrap_baseline: 'incomplete', agents: 'missing', skills: 'missing',
      current_state: 'missing', codebase: 'missing', capabilities: 'missing', product: 'missing', business: 'missing',
      roadmap: 'missing', work_items: 'none', adapters: [],
      blocking_open_questions: 0, assumed_questions: 0, resolved_questions: 0, deferred_questions: 0,
    },
    recommended_next_step: { label, ...(command ? { command } : {}) },
  })

  if (!config) return stub('not-initialized', 'Run `kaddo init` to initialize Kaddo.', 'kaddo init')
  if (config.project.state === 'new') return stub('not-applicable', 'This project uses the standard new-project Kaddo flow.')
  if (config.project.state === 'legacy') return stub('legacy-project', 'Use the legacy project flow.')

  const scan = exists(join(dir, '.kaddo', 'scan.json')) ? 'available' : 'missing'
  const understand = exists(join(dir, '.kaddo', 'understand.md')) ? 'available' : 'missing'
  const presence = Object.fromEntries(KNOWLEDGE_FILES.map((f) => [f.key, knowledgePresence(dir, f.path)])) as Record<typeof KNOWLEDGE_FILES[number]['key'], Presence>
  const ctx = buildCodexAdapterContext(dir)
  const agents = ctx.hasAgents ? 'present' : 'missing'
  const skills = ctx.hasSkills ? 'present' : 'missing'
  // Bootstrap baseline = the core business + product knowledge the bootstrap step produces.
  const bootstrapBaseline = presence.business !== 'missing' && presence.product !== 'missing' ? 'complete' : 'incomplete'
  const roadmap = roadmapSignal(dir)
  const work_items = workItemsSignal(dir)
  const adapters = installedAdapters(dir)
  const oq = buildOpenQuestionsReport(dir, now)

  const signals: ReadinessReport['signals'] = {
    scan, understand, bootstrap_baseline: bootstrapBaseline, agents, skills,
    current_state: presence.current_state, codebase: presence.codebase, capabilities: presence.capabilities,
    product: presence.product, business: presence.business,
    roadmap, work_items, adapters,
    blocking_open_questions: oq.summary.blocking_open,
    assumed_questions: oq.summary.resolution.assumed,
    resolved_questions: oq.summary.resolution.resolved,
    deferred_questions: oq.summary.resolution.deferred,
  }

  let overall: ReadinessStatus
  let next: { label: string; command?: string }
  const firstWeak = KNOWLEDGE_FILES.find((f) => presence[f.key] !== 'present')

  if (scan === 'missing') {
    overall = 'initialized'
    next = { label: 'Run `kaddo scan` to capture deterministic signals from the existing code.', command: 'kaddo scan' }
  } else if (bootstrapBaseline === 'incomplete') {
    overall = 'bootstrap-incomplete'
    next = { label: 'Run `kaddo bootstrap` to create the project knowledge baseline.', command: 'kaddo bootstrap' }
  } else if (agents === 'missing') {
    overall = 'agents-missing'
    next = { label: 'Run `kaddo add agents` to install the Kaddo agent prompt packs.', command: 'kaddo add agents' }
  } else if (skills === 'missing') {
    overall = 'skills-missing'
    next = { label: 'Run `kaddo add skills` to install reusable Kaddo skills.', command: 'kaddo add skills' }
  } else if (understand === 'missing') {
    overall = 'scanned'
    next = { label: 'Run `kaddo understand` to summarize the project context.', command: 'kaddo understand' }
  } else if (firstWeak) {
    overall = 'knowledge-incomplete'
    next = { label: `Complete \`${firstWeak.label}\` (it is ${presence[firstWeak.key]}).` }
  } else if (oq.summary.blocking_open > 0) {
    overall = 'needs-decisions'
    next = { label: 'Resolve, assume or defer the blocking open questions (`kaddo questions`).', command: 'kaddo questions' }
  } else if (roadmap !== 'has-candidates') {
    overall = 'ready-for-roadmap'
    next = { label: 'Run `kaddo roadmap` to draft the roadmap from the current knowledge.', command: 'kaddo roadmap' }
  } else if (work_items === 'none' || work_items === 'none-ready') {
    overall = 'ready-for-work-item'
    next = { label: 'Run `kaddo create --from roadmap` to materialize the first Work Item.', command: 'kaddo create --from roadmap' }
  } else {
    overall = 'ready-for-implementation'
    next = adapters.length > 0
      ? { label: 'Implement the ready Work Item and run `kaddo guard`.' }
      : { label: 'Run `kaddo adapters list` and install the adapter for your preferred agent.', command: 'kaddo adapters list' }
  }

  return { project_name: config.project.name, project_type: config.project.state, overall, signals, recommended_next_step: next }
}
