import type { ContextPack } from '../core/context-pack.js'
import { presentArtifacts } from '../services/mapped-modules.js'
import { renderLayersMarkdown } from '../core/layers.js'

function stateLabel(state: string): string {
  return state === 'pre-ai' ? 'pre-AI' : state
}

/**
 * Render an LLM-friendly markdown context pack.
 * Deterministic, concise — meant to be pasted into a chat alongside a Kaddo agent prompt.
 */
export function renderContextPack(pack: ContextPack): string {
  const { project, scan, knowledge, missing, handoff } = pack
  const parts: string[] = []

  parts.push('# Kaddo Context Pack\n')
  parts.push(
    '> Generated by `kaddo context`. Deterministic CLI output — not an interpretation of the system.\n'
  )

  // 0. Operating Rules — read first (prevents the agent from committing on its own).
  parts.push('## Operating Rules (read first)\n')
  parts.push(handoff.operatingRules.map((r) => `- ${r}`).join('\n') + '\n')

  // 1. Project Metadata
  parts.push('## Project Metadata\n')
  parts.push(
    [
      `- Name: ${project.name}`,
      `- State: ${project.state}`,
      `- Team size: ${project.teamSize}`,
      `- Structure: ${project.structure}`,
      `- Language: ${project.language}`,
    ].join('\n') + '\n'
  )

  // 1a. Current phase + recommended next agent (VS-047) — state-aware, not just project.state.
  parts.push('## Current Phase\n')
  parts.push(`Phase: ${pack.phase.phase}\n`)
  if (pack.phase.reasons.length > 0) {
    parts.push('Reason:\n')
    parts.push(pack.phase.reasons.map((r) => `- ${r}`).join('\n') + '\n')
  }
  if (pack.phase.recommendedAgents.length > 0) {
    parts.push(`Recommended next: ${pack.phase.recommendedAgents.join(', ')}\n`)
  }
  if (pack.phase.nextStep) {
    parts.push(`Next step: ${pack.phase.nextStep}\n`)
  }

  // 1b. Knowledge Layers + maturity (Business → Product → Tech → Delivery)
  parts.push('## Knowledge Layers\n')
  parts.push(
    'Project knowledge is organized in four layers: **Business → Product → Tech → Delivery**.\n'
  )
  const maturity = pack.layers.map((l) => `${l.layer}: ${l.status}`).join(' · ')
  parts.push(`Knowledge maturity — ${maturity}\n`)
  parts.push(renderLayersMarkdown(pack.layers) + '\n')

  // 2. Technical Inventory
  parts.push('## Technical Inventory\n')
  if (scan.available) {
    const lines = [
      `- Language: ${scan.languages.join(', ') || 'unknown'}`,
      `- Framework: ${scan.frameworks.join(', ') || 'unknown'}`,
      `- Package manager: ${scan.packageManagers.join(', ') || 'unknown'}`,
    ]
    if (scan.sourceDirectories.length > 0) {
      lines.push('- Source directories:')
      scan.sourceDirectories.forEach((d) => lines.push(`  - ${d}`))
    }
    if (scan.migrationDirectories.length > 0) {
      lines.push('- Migration directories:')
      scan.migrationDirectories.forEach((d) => lines.push(`  - ${d}`))
    }
    if (scan.contractFiles.length > 0) {
      lines.push('- Contracts:')
      scan.contractFiles.forEach((f) => lines.push(`  - ${f}`))
    }
    if (scan.infrastructureFiles.length > 0) {
      lines.push('- Infrastructure:')
      scan.infrastructureFiles.forEach((f) => lines.push(`  - ${f}`))
    }
    parts.push(lines.join('\n') + '\n')
  } else {
    parts.push('Scan baseline missing. Run `kaddo scan` for better context.\n')
  }

  // 3. Current Knowledge
  parts.push('## Current Knowledge\n')
  parts.push((knowledge.summary || 'No project knowledge summary found yet.') + '\n')

  // 4. Roadmap
  parts.push('## Roadmap\n')
  if (pack.roadmap.present) {
    parts.push(
      [
        `- Roadmap candidates: ${pack.roadmap.candidates}`,
        `- Materialized work items: ${pack.roadmap.materialized}`,
        `- Remaining candidates: ${pack.roadmap.remaining}`,
      ].join('\n') + '\n'
    )
    if (pack.roadmap.remaining > 0) {
      parts.push(
        'Candidates are not yet Work Items. Materialize them with `kaddo create --from roadmap`.\n'
      )
    }
  }
  parts.push((knowledge.roadmapSummary || 'No roadmap baseline found.') + '\n')

  // 5. Active Work Items
  parts.push('## Active Work Items\n')
  if (knowledge.workItems.length > 0) {
    const lines = knowledge.workItems.map((wi) => {
      const level = wi.knowledgeLevel ? ` [${wi.knowledgeLevel}]` : ''
      const status = wi.lifecycle ? ` (${wi.lifecycle})` : wi.status ? ` (${wi.status})` : ''
      const domains = wi.domains.length > 0 ? ` · domains: ${wi.domains.join(', ')}` : ''
      return `- ${wi.id || wi.title} [${wi.type}]${level}${status} — ${wi.title}${domains}`
    })
    parts.push(lines.join('\n') + '\n')
  } else {
    parts.push('No active work items found.\n')
  }

  // 5b. Delivery Mix — active Work Items by type (VS-045)
  const mixEntries = Object.entries(pack.deliveryMix).sort((a, b) => b[1] - a[1])
  if (mixEntries.length > 0) {
    parts.push('## Delivery Mix\n')
    parts.push('Active Work Items by type:\n')
    const label = (t: string) => {
      const c = t.charAt(0).toUpperCase() + t.slice(1)
      return c.endsWith('s') ? c : `${c}s`
    }
    parts.push(mixEntries.map(([t, n]) => `- ${label(t)}: ${n}`).join('\n') + '\n')
  }

  // 6. Artifacts and Ownership
  parts.push('## Artifacts and Ownership\n')
  if (knowledge.artifacts.length > 0) {
    const lines = knowledge.artifacts.map(
      (a) => `- ${a.id || a.title} [${a.type}] owns: ${a.codeGlobs.join(', ')}`
    )
    parts.push(lines.join('\n') + '\n')
  } else {
    parts.push('No artifacts declare code ownership yet.\n')
  }

  // 6b. Mapped Modules (multirepo)
  if (pack.mappedModules.length > 0) {
    parts.push('## Mapped Modules\n')
    parts.push('This project has mapped modules registered in `.kaddo/modules.yml`.\n')
    const header = '| Module | Type | Repo path | Owner | Capabilities | Artifacts |'
    const sep = '|---|---|---|---|---|---|'
    const rows = pack.mappedModules.map((m) => {
      const caps = m.capabilities.length > 0 ? m.capabilities.join(', ') : '—'
      const arts = presentArtifacts(m.artifacts)
      return `| ${m.id} | ${m.type ?? '—'} | ${m.repoPath || '—'} | ${m.owner ?? '—'} | ${caps} | ${arts.length > 0 ? arts.join(', ') : 'none'} |`
    })
    parts.push([header, sep, ...rows].join('\n') + '\n')
    parts.push(
      'Note: Kaddo does not scan secondary repositories during `context`. Mapped modules ' +
        'come from `.kaddo/modules.yml` and module artifacts only.\n'
    )
  }

  // 7. Missing Context
  parts.push('## Missing Context\n')
  if (missing.length > 0) {
    parts.push(missing.map((m) => `- ${m}`).join('\n') + '\n')
  } else {
    parts.push('_None — all expected context is present._\n')
  }

  // 8. Recommended Agent Handoff
  parts.push('## Recommended Agent Handoff\n')
  parts.push(`Recommended agents for a ${stateLabel(project.state)} project:\n`)
  parts.push(handoff.recommendedAgents.map((a, i) => `${i + 1}. ${a}`).join('\n') + '\n')
  if (handoff.nextSteps.length > 0) {
    parts.push('Next steps:\n')
    parts.push(handoff.nextSteps.map((s) => `- ${s}`).join('\n') + '\n')
  }

  // 9. Instructions for the LLM
  parts.push('## Instructions for the LLM\n')
  parts.push(handoff.instructions.map((i) => `- ${i}`).join('\n') + '\n')

  return parts.join('\n')
}
