import type { ContextPack } from '../core/context-pack.js'
import { presentArtifacts } from '../services/mapped-modules.js'
import { renderLayersMarkdown } from '../core/layers.js'
import { renderRouteCompact } from '../core/project-route.js'
import { renderSignalsCompact, signalCount } from '../core/scan-signals.js'
import { renderSourceCompact } from '../core/work-item-source.js'

/**
 * Render an LLM-friendly markdown context pack.
 * Deterministic, concise — meant to be pasted into a chat alongside a Kaddo agent prompt.
 */
export function renderContextPack(pack: ContextPack): string {
  const { project, scan, knowledge, missing, handoff } = pack
  const parts: string[] = []

  parts.push('# Kaddo Context Pack\n')
  parts.push(
    '> Generated by `kaddo context`. Deterministic CLI output — not an interpretation of the system.\n'
  )

  // 0. Operating Rules — read first (prevents the agent from committing on its own).
  parts.push('## Operating Rules (read first)\n')
  parts.push(handoff.operatingRules.map((r) => `- ${r}`).join('\n') + '\n')

  // 1. Project Metadata
  parts.push('## Project Metadata\n')
  parts.push(
    [
      `- Name: ${project.name}`,
      `- State: ${project.state}`,
      `- Team size: ${project.teamSize}`,
      `- Structure: ${project.structure}`,
      `- Language: ${project.language}`,
    ].join('\n') + '\n'
  )

  // 1a. Current phase + recommended next agent (VS-047) — state-aware, not just project.state.
  parts.push('## Current Phase\n')
  parts.push(`Phase: ${pack.phase.phase}\n`)
  if (pack.phase.reasons.length > 0) {
    parts.push('Reason:\n')
    parts.push(pack.phase.reasons.map((r) => `- ${r}`).join('\n') + '\n')
  }
  if (pack.phase.recommendedAgents.length > 0) {
    parts.push(`Recommended next: ${pack.phase.recommendedAgents.join(', ')}\n`)
  }
  if (pack.phase.nextStep) {
    parts.push(`Next step: ${pack.phase.nextStep}\n`)
  }

  // 1a-delivery. State-aware delivery snapshot + next-step recommendation (VS-079).
  const ds = pack.deliveryState
  const rec = pack.nextStepRecommendation
  if (ds.total_work_items > 0 || rec.phase !== 'Setup') {
    parts.push('## Delivery State\n')
    parts.push(
      [
        `- Phase: ${ds.phase}`,
        `- Draft Work Items: ${ds.draft_work_items}`,
        `- Ready Work Items: ${ds.ready_work_items}`,
        `- In-progress Work Items: ${ds.in_progress_work_items}`,
        `- Ownership coverage: ${ds.ownership_coverage}`,
        `- Remaining Work Item candidates: ${ds.remaining_work_item_candidates}`,
      ].join('\n') + '\n'
    )
    parts.push('## Next Step Recommendation\n')
    const recLines = [`- ${rec.label}`, `  - id: ${rec.id}`, `  - reason: ${rec.reason}`]
    if (rec.agent) recLines.push(`  - agent: ${rec.agent}`)
    if (rec.skill) recLines.push(`  - skill: ${rec.skill}`)
    if (rec.command) recLines.push(`  - command: \`${rec.command}\``)
    parts.push(recLines.join('\n') + '\n')
    if (rec.secondary && rec.secondary.length > 0) {
      parts.push('Also (secondary):\n')
      parts.push(rec.secondary.map((s) => `- ${s.label}`).join('\n') + '\n')
    }
  }

  // 1a-route. Project Route progress map (VS-080).
  parts.push('## Project Route\n')
  parts.push(renderRouteCompact(pack.projectRoute))

  // 1b. Knowledge Layers + maturity (Business → Product → Tech → Delivery)
  parts.push('## Knowledge Layers\n')
  parts.push(
    'Project knowledge is organized in four layers: **Business → Product → Tech → Delivery**.\n'
  )
  const maturity = pack.layers.map((l) => `${l.layer}: ${l.status}`).join(' · ')
  parts.push(`Knowledge maturity — ${maturity}\n`)
  parts.push(renderLayersMarkdown(pack.layers) + '\n')

  // 2. Technical Inventory
  parts.push('## Technical Inventory\n')
  if (scan.available) {
    const lines = [
      `- Language: ${scan.languages.join(', ') || 'unknown'}`,
      `- Framework: ${scan.frameworks.join(', ') || 'unknown'}`,
      `- Package manager: ${scan.packageManagers.join(', ') || 'unknown'}`,
    ]
    if (scan.sourceDirectories.length > 0) {
      lines.push('- Source directories:')
      scan.sourceDirectories.forEach((d) => lines.push(`  - ${d}`))
    }
    if (scan.migrationDirectories.length > 0) {
      lines.push('- Migration directories:')
      scan.migrationDirectories.forEach((d) => lines.push(`  - ${d}`))
    }
    if (scan.contractFiles.length > 0) {
      lines.push('- Contracts:')
      scan.contractFiles.forEach((f) => lines.push(`  - ${f}`))
    }
    if (scan.infrastructureFiles.length > 0) {
      lines.push('- Infrastructure:')
      scan.infrastructureFiles.forEach((f) => lines.push(`  - ${f}`))
    }
    parts.push(lines.join('\n') + '\n')
  } else {
    parts.push('Scan baseline missing. Run `kaddo scan` for better context.\n')
  }

  // 2b. Scan Signals (VS-081)
  if (pack.scanSignals && signalCount(pack.scanSignals) > 0) {
    parts.push('## Scan Signals\n')
    parts.push(renderSignalsCompact(pack.scanSignals))
  }

  // 3. Current Knowledge
  parts.push('## Current Knowledge\n')
  parts.push((knowledge.summary || 'No project knowledge summary found yet.') + '\n')

  // 4. Roadmap Status (VS-077.1) — initiatives vs Work Item candidates vs materialization.
  parts.push('## Roadmap Status\n')
  if (pack.roadmap.present) {
    parts.push(
      [
        `- Initiatives: ${pack.roadmap.initiatives}`,
        `- Work Item candidates: ${pack.roadmap.work_item_candidates}`,
        `- Materialized Work Items: ${pack.roadmap.materialized_work_items}`,
        `- Remaining Work Item candidates: ${pack.roadmap.remaining_work_item_candidates}`,
      ].join('\n') + '\n'
    )
    if (pack.roadmap.remaining_work_item_candidates > 0) {
      parts.push(
        'Work Item candidates are not yet Work Items. Materialize them with `kaddo create --from roadmap`.\n'
      )
    }
  }
  parts.push((knowledge.roadmapSummary || 'No roadmap baseline found.') + '\n')

  // 4b. Roadmap Quality (VS-077 / VS-077.1) — grade initiatives and Work Item candidates separately.
  const rq = pack.roadmapQuality
  const rqi = rq.initiatives
  const rqw = rq.work_item_candidates
  if (rqi.total > 0 || rqw.total > 0) {
    parts.push('## Roadmap Quality\n')
    if (rqi.total > 0) {
      parts.push(
        [
          'Initiatives:',
          `- Candidates evaluated: ${rqi.total}`,
          `- Grounded: ${rqi.grounded}/${rqi.total}`,
          `- With related domain: ${rqi.with_related_domain}/${rqi.total}`,
          `- With related capability: ${rqi.with_related_capability}/${rqi.total}`,
          `- With source signals: ${rqi.with_source_signals}/${rqi.total}`,
        ].join('\n') + '\n'
      )
    }
    if (rqw.total > 0) {
      parts.push(
        [
          'Work Item Candidates:',
          `- Candidates: ${rqw.total}`,
          `- With source initiative: ${rqw.with_source_initiative}/${rqw.total}`,
          `- With related domain: ${rqw.with_related_domain}/${rqw.total}`,
          `- With related capability: ${rqw.with_related_capability}/${rqw.total}`,
        ].join('\n') + '\n'
      )
    }
    if (rqi.needs_refinement) {
      parts.push(
        'Roadmap quality: needs refinement. Use the roadmap-agent to add domain / capability / source signals.\n'
      )
    }
  }

  // 5. Active Work Items
  parts.push('## Active Work Items\n')
  if (knowledge.workItems.length > 0) {
    const lines = knowledge.workItems.map((wi) => {
      const level = wi.knowledgeLevel ? ` [${wi.knowledgeLevel}]` : ''
      const status = wi.lifecycle ? ` (${wi.lifecycle})` : wi.status ? ` (${wi.status})` : ''
      const domains = wi.domains.length > 0 ? ` · domains: ${wi.domains.join(', ')}` : ''
      const line = `- ${wi.id || wi.title} [${wi.type}]${level}${status} — ${wi.title}${domains}`
      const src = wi.source && wi.source.type !== 'unknown' ? `\n  - Source: ${renderSourceCompact(wi.source)}` : ''
      return `${line}${src}`
    })
    parts.push(lines.join('\n') + '\n')
  } else {
    parts.push('No active work items found.\n')
  }

  // 5b. Delivery Mix — active Work Items by type (VS-045)
  const mixEntries = Object.entries(pack.deliveryMix).sort((a, b) => b[1] - a[1])
  if (mixEntries.length > 0) {
    parts.push('## Delivery Mix\n')
    parts.push('Active Work Items by type:\n')
    const label = (t: string) => {
      const c = t.charAt(0).toUpperCase() + t.slice(1)
      return c.endsWith('s') ? c : `${c}s`
    }
    parts.push(mixEntries.map(([t, n]) => `- ${label(t)}: ${n}`).join('\n') + '\n')
  }

  // 6. Artifacts and Ownership
  parts.push('## Artifacts and Ownership\n')
  if (knowledge.artifacts.length > 0) {
    const lines = knowledge.artifacts.map(
      (a) => `- ${a.id || a.title} [${a.type}] owns: ${a.codeGlobs.join(', ')}`
    )
    parts.push(lines.join('\n') + '\n')
  } else {
    parts.push('No artifacts declare code ownership yet.\n')
  }

  // 6b. Mapped Modules (multirepo)
  if (pack.mappedModules.length > 0) {
    parts.push('## Mapped Modules\n')
    parts.push('This project has mapped modules registered in `.kaddo/modules.yml`.\n')
    const header = '| Module | Type | Repo path | Owner | Capabilities | Artifacts |'
    const sep = '|---|---|---|---|---|---|'
    const rows = pack.mappedModules.map((m) => {
      const caps = m.capabilities.length > 0 ? m.capabilities.join(', ') : '—'
      const arts = presentArtifacts(m.artifacts)
      return `| ${m.id} | ${m.type ?? '—'} | ${m.repoPath || '—'} | ${m.owner ?? '—'} | ${caps} | ${arts.length > 0 ? arts.join(', ') : 'none'} |`
    })
    parts.push([header, sep, ...rows].join('\n') + '\n')
    parts.push(
      'Note: Kaddo does not scan secondary repositories during `context`. Mapped modules ' +
        'come from `.kaddo/modules.yml` and module artifacts only.\n'
    )
    // VS-091: module configuration status warnings.
    const statuses = pack.moduleStatuses ?? {}
    const warnings = Object.entries(statuses).filter(([, s]) => s.warning)
    if (warnings.length > 0) {
      parts.push('### Module Warnings\n')
      for (const [id, s] of warnings) {
        parts.push(`- **${id}** (${s.status}): ${s.warning}\n`)
      }
    }
  }

  // VS-091: affected module contexts for active Work Items.
  const affectedCtx = pack.affectedModuleContexts ?? {}
  const affectedIds = Object.keys(affectedCtx)
  if (affectedIds.length > 0) {
    parts.push('## Affected Module Contexts\n')
    parts.push('The following module contexts are included because active Work Items reference them via `affected_modules`.\n')
    for (const id of affectedIds) {
      parts.push(`### Module: ${id}\n`)
      parts.push(affectedCtx[id] + '\n')
    }
  }

  // 6c. External Knowledge — imported Knowledge Capsules (VS-054).
  if (pack.external.length > 0) {
    parts.push('## External Knowledge\n')
    parts.push(
      'Imported Knowledge Capsules — minimal context about external systems (not their source).\n'
    )
    for (const cap of pack.external) {
      const lines = [`### ${cap.system}`, '']
      if (cap.purpose) lines.push(`- Purpose: ${cap.purpose}`)
      if (cap.capabilities.length) lines.push(`- Capabilities: ${cap.capabilities.join(', ')}`)
      if (cap.contracts.length) lines.push(`- Contracts: ${cap.contracts.join(', ')}`)
      if (cap.owner) lines.push(`- Owner: ${cap.owner}`)
      if (cap.knownRisks.length) lines.push(`- Known risks: ${cap.knownRisks.join('; ')}`)
      parts.push(lines.join('\n') + '\n')
    }
  }

  // 6d. Knowledge Graph — a summary only (the full graph lives in .kaddo/graph.json/.mmd). VS-055.
  if (pack.graph) {
    parts.push('## Knowledge Graph\n')
    parts.push(
      [
        '- Available: yes',
        `- Scope: ${pack.graph.scope}`,
        `- Nodes: ${pack.graph.nodes}`,
        `- Edges: ${pack.graph.edges}`,
        ...(pack.graphHints ? [`- Quality: ${pack.graphHints.quality}`] : []),
        `- Active Work Items connected to code: ${pack.graph.activeWorkItemsConnectedToCode}`,
        ...(pack.graph.scopeReason ? [`- Reason: ${pack.graph.scopeReason}`] : []),
      ].join('\n') + '\n'
    )
    parts.push('Full graph: `.kaddo/graph.json` / `.kaddo/graph.mmd` (run `kaddo graph export` to refresh).\n')
  }

  // 6e. Graph Hints — relationship-quality summary (VS-056). Short by design: a few messages
  // only, not the whole graph-hints.md file.
  if (pack.graphHints && pack.graphHints.totalHints > 0) {
    parts.push('## Graph Hints\n')
    parts.push(
      [
        `Graph relationship quality: ${pack.graphHints.quality}`,
        `Active hints: ${pack.graphHints.activeWorkItemHints}`,
        'Suggested agent: graph-agent',
      ].join('\n') + '\n'
    )
    const shown = pack.graphHints.messages.slice(0, 3)
    parts.push(shown.map((m) => `- ${m}`).join('\n') + '\n')
    if (pack.graphHints.totalHints > shown.length) {
      parts.push(`(+${pack.graphHints.totalHints - shown.length} more in \`.kaddo/graph-hints.md\`)\n`)
    }
  }

  // 6f. Skills — reusable capabilities (VS-059). Summary only: list ids, not full content.
  if (pack.skills.length > 0) {
    parts.push('## Skills\n')
    parts.push('Available reusable skills (agents apply these; content is not inlined):\n')
    parts.push(pack.skills.map((s) => `- ${s}`).join('\n') + '\n')
    parts.push('Read full skill definitions in `knowledge/skills/` or via the Kaddo MCP server (`kaddo://skills`).\n')
  }

  // 7. Missing Context
  const isBootstrapIncomplete = rec.id === 'bootstrap'
  parts.push('## Missing Context\n')
  if (isBootstrapIncomplete) {
    const baselineMissing = [
      '- Bootstrap baseline is incomplete.',
      ...(!pack.knowledgeQuality.business || pack.knowledgeQuality.business.status === 'Missing' ? ['- Missing business knowledge.'] : []),
      ...(!pack.knowledgeQuality.product || pack.knowledgeQuality.product.status === 'Missing' ? ['- Missing product knowledge.'] : []),
    ]
    if (missing.length > 0) {
      baselineMissing.push(...missing.filter((m) => !baselineMissing.some((b) => b.includes(m))))
    }
    parts.push(baselineMissing.join('\n') + '\n')
  } else if (missing.length > 0) {
    parts.push(missing.map((m) => `- ${m}`).join('\n') + '\n')
  } else {
    parts.push('_None — all expected context is present._\n')
  }

  // Metadata health warnings (VS-084): frontmatter drift is separate from content quality.
  if (pack.metadataHealth.findings.length > 0) {
    parts.push('\n### Metadata Health\n')
    for (const f of pack.metadataHealth.findings) {
      parts.push(`- \`${f.file}\`: ${f.detail}\n`)
    }
  }

  // 8. Recommended Agent Handoff — driven by the real phase (VS-052), so it agrees with the
  // Current Phase block above instead of recommending early-stage agents by project.state.
  parts.push('## Recommended Agent Handoff\n')
  if (isBootstrapIncomplete) {
    parts.push('No agent handoff yet.\n')
    parts.push('Run `kaddo bootstrap` first to create the baseline files.\n')
  } else if (rec.agent && rec.agentInstalled === false) {
    parts.push(`Recommended agent: ${rec.agent.replace(/\.md$/, '')}\n`)
    parts.push('**Agent is not installed.**\n')
    if (rec.installCommand) {
      parts.push(`Run \`${rec.installCommand}\` to install it.\n`)
    }
    parts.push('Then run `kaddo context` and `kaddo understand`.\n')
  } else {
    parts.push(`Recommended next for the **${pack.phase.phase}** phase:\n`)
    if (rec.agentPath) {
      parts.push(`Agent prompt: \`${rec.agentPath}\`\n`)
    }
    parts.push(handoff.recommendedAgents.map((a, i) => `${i + 1}. ${a}`).join('\n') + '\n')
    if (handoff.nextSteps.length > 0) {
      parts.push('Next step:\n')
      parts.push(handoff.nextSteps.map((s) => `- ${s}`).join('\n') + '\n')
    }
  }

  // 9. Instructions for the LLM — phase-specific (VS-052).
  parts.push('## Instructions for the LLM\n')
  parts.push(handoff.instructions.map((i) => `- ${i}`).join('\n') + '\n')

  return parts.join('\n')
}
