import type { ScanBaseline } from '../core/scan-baseline.js'

function section(title: string, items: string[], emptyNote = '_(none detected)_'): string {
  const body = items.length > 0 ? items.map((i) => `- ${i}`).join('\n') : emptyNote
  return `## ${title}\n\n${body}\n`
}

/**
 * Render a human-readable inventory from a scan baseline.
 * This is the surface humans read and paste into an LLM chat — concise and deterministic.
 */
export function renderInventory(baseline: ScanBaseline): string {
  const { project, detected, suggestions } = baseline

  const parts: string[] = []

  parts.push('# Project Inventory\n')
  parts.push(
    '> Generated by `kaddo scan`. Deterministic technical baseline — not an interpretation of the system.\n'
  )

  parts.push(
    section('Project Context', [
      `State: ${project.state}`,
      `Structure: ${project.structure}`,
      `Team size: ${project.teamSize}`,
    ])
  )

  parts.push(
    section('Detected Stack', [
      `Language: ${detected.languages.join(', ') || 'unknown'}`,
      `Framework: ${detected.frameworks.join(', ') || 'unknown'}`,
      `Package manager: ${detected.packageManagers.join(', ') || 'unknown'}`,
    ])
  )

  parts.push(section('Source Directories', detected.sourceDirectories.map((d) => `${d}/`)))
  parts.push(section('Migrations', detected.migrationDirectories.map((d) => `${d}/`)))
  parts.push(section('Contracts', detected.contractFiles))
  parts.push(section('Infrastructure', detected.infrastructureFiles))
  parts.push(section('Tests', detected.testDirectories.map((d) => `${d}/`)))
  parts.push(section('Possible Domains', suggestions.possibleDomains))
  parts.push(section('Open Questions', suggestions.openQuestions))

  return parts.join('\n')
}
