import type { UnderstandPlan } from '../core/understand.js'

function stateLabel(state: string): string {
  return state === 'pre-ai' ? 'pre-AI' : state
}

function agentName(file: string): string {
  return file.replace(/\.md$/, '')
}

/**
 * Render the reusable `.kaddo/understand.md` handoff guide.
 * Deterministic — explains how to use the context pack + agents in an LLM chat.
 */
export function renderUnderstand(plan: UnderstandPlan): string {
  const { project, steps } = plan
  const parts: string[] = []

  parts.push('# Kaddo Understand Handoff\n')
  parts.push(
    '> Generated by `kaddo understand`. Kaddo does not call an LLM — you stay in control of the interpretation.\n'
  )

  // Project
  parts.push('## Project\n')
  parts.push(
    [
      `- Name: ${project.name}`,
      `- State: ${project.state}`,
      `- Team: ${project.teamSize}`,
      `- Structure: ${project.structure}`,
    ].join('\n') + '\n'
  )

  // Recommended Agent Flow
  parts.push('## Recommended Agent Flow\n')
  parts.push(`Recommended order for a ${stateLabel(project.state)} project:\n`)
  parts.push(
    steps
      .map((s, i) => {
        const flag = s.installed ? '' : '  _(not installed — run `kaddo add agents`)_'
        return `${i + 1}. ${agentName(s.agent)} → \`${s.output}\`${flag}`
      })
      .join('\n') + '\n'
  )

  // Context Pack
  parts.push('## Context Pack\n')
  const scanNote = plan.scanAvailable
    ? ''
    : ' (incomplete — run `kaddo scan` first for a richer baseline)'
  parts.push(`Use \`${plan.contextPackPath}\` as the primary input${scanNote}.\n`)

  // Agent Prompts
  parts.push('## Agent Prompts\n')
  parts.push(
    steps.map((s) => `- \`architecture/agents/${s.agent}\``).join('\n') + '\n'
  )

  // Expected Outputs
  parts.push('## Expected Outputs\n')
  parts.push(steps.map((s) => `- \`${s.output}\``).join('\n') + '\n')

  // Copy/Paste Instructions
  parts.push('## Copy/Paste Instructions\n')
  const first = steps[0]
  if (first) {
    parts.push(
      [
        `Start with **${agentName(first.agent)}**:`,
        '',
        '1. Open your preferred LLM chat (Claude, ChatGPT, Cursor, Copilot, Windsurf…).',
        `2. Paste the context pack: \`${plan.contextPackPath}\``,
        `3. Paste the agent prompt: \`architecture/agents/${first.agent}\``,
        `4. Ask the LLM to produce: \`${first.output}\``,
        `5. Save the result in: \`${first.output}\``,
      ].join('\n') + '\n'
    )
  }

  // Next Steps
  parts.push('## Next Steps\n')
  if (steps.length > 1) {
    parts.push(
      `After saving \`${steps[0].output}\`, continue with **${agentName(steps[1].agent)}** ` +
        `(feed it the context pack plus the artifacts you already produced). Re-run ` +
        '`kaddo understand` any time to see this plan again.\n'
    )
  } else {
    parts.push('Re-run `kaddo understand` any time to see this plan again.\n')
  }

  return parts.join('\n')
}

/** Render the concise terminal summary (printed by the command). */
export function renderUnderstandTerminal(plan: UnderstandPlan): string {
  const { project, steps } = plan
  const lines: string[] = []

  lines.push('')
  lines.push('Kaddo Understand')
  lines.push('')
  lines.push(`Project: ${project.name}`)
  lines.push(`State: ${project.state}`)
  lines.push(`Team: ${project.teamSize}`)
  lines.push(`Structure: ${project.structure}`)
  lines.push('')
  lines.push('Recommended flow:')
  steps.forEach((s, i) => {
    const flag = s.installed ? '' : '  (not installed)'
    lines.push(`  ${i + 1}. ${agentName(s.agent)} → ${s.output}${flag}`)
  })
  lines.push('')

  const first = steps[0]
  if (first) {
    lines.push(`First step: use ${agentName(first.agent)}.`)
    lines.push('')
    lines.push(`  Context:         ${plan.contextPackPath}`)
    lines.push(`  Agent prompt:    architecture/agents/${first.agent}`)
    lines.push(`  Expected output: ${first.output}`)
    lines.push('')
  }

  lines.push('Instructions:')
  lines.push('  Open your preferred LLM chat, paste the context pack, then paste the agent')
  lines.push('  prompt. Ask the LLM to generate the expected output and save it in the target file.')
  lines.push('')
  lines.push('Kaddo does not call an LLM. You stay in control of the interpretation.')
  lines.push('')

  return lines.join('\n')
}
