// Public core API for consumption by Admin and other interfaces (VS-096).
// These re-exports allow Admin Server to import domain logic from @kaddo/cli/core
// without shelling out to CLI commands.

export { buildProjectExplanation, type ProjectExplanation } from './core/project-explain.js'
export { buildReadinessReport, type ReadinessReport, type ReadinessStatus } from './core/readiness.js'
export { buildProjectRoute, type ProjectRoute, type RouteStep, type RouteStepStatus } from './core/project-route.js'
export { knowledgeLayers, type LayerStatus, type LayerName, type LayerMaturity } from './core/layers.js'
export { loadConfig, isModule, type KaddoConfig, type ProjectState, type RepositoryStructure } from './core/config.js'
export { discoverKnowledge, discoverWorkItems, type KnowledgeArtifact, type KnowledgeLayer } from './services/knowledge-artifacts.js'
export { loadMappedModules, type MappedModuleWithCoverage } from './services/mapped-modules.js'
export { lifecycleStateOf, lifecycleCounts, isActiveState, type LifecycleState } from './core/lifecycle.js'
export { analyzeScopeCoverage, type ScopeCoverageSummary } from './core/scope-coverage.js'
export { analyzeCrossRepoEvidence } from './core/cross-repo-evidence.js'
export {
  getWorkItemsSummary,
  getWorkItems,
  getWorkItem,
  WorkItemNotFoundError,
  type WorkItemsSummary,
  type WorkItemListItem,
  type WorkItemsResult,
  type WorkItemFilters,
  type WorkItemDetail,
  type CoverageEntry,
  type ImpactEntry,
  type AcceptanceCriterion,
  type ReleaseGateEntry,
  type CompletionExceptionEntry,
  type EvidenceRepo,
  type LinkedDecision,
  type LinkedKnowledge,
  type SystemImpactEntity,
  type ReviewedSystemEntity,
  type SystemImpactGraphReason,
} from './core/work-items.js'
export {
  createWorkItem,
  updateWorkItem,
  getWorkItemForEdit,
  validateWorkItem,
  transitionWorkItem,
  WorkItemWriteError,
  type WorkItemInput,
  type WorkItemSourceInput,
  type ExternalSnapshot,
  type WorkItemEditModel,
  type WorkItemCoverageInput,
  type WorkItemImpactInput,
  type WorkItemCriterionInput,
  type ValidationFinding,
  type ValidationResult,
  type WriteErrorCode,
} from './core/work-item-write.js'
export {
  getWorkItemCaptureDefinition,
  buildRefinementHandoff,
  type WorkItemCaptureDefinition,
  type CaptureQuestion,
  type RefinementHandoff,
} from './core/work-item-refinement.js'
export { computeRefinementStatus, type RefinementStatus } from './core/work-items.js'
export {
  importWorkItem,
  detectFormat,
  parseContent,
  computeContentHash,
  findDuplicateByHash,
  findExistingById,
  ImportError,
  type ImportWorkItemOpts,
  type ImportWorkItemResult,
  type IdConflict,
  type DetectedFormat,
  type ParsedContent,
  type ImportErrorCode,
} from './core/work-item-import.js'
export {
  getSystemMapProjection,
  getSystemNodeContext,
  searchSystemNodes,
  getSystemNeighbors,
  findSystemPaths,
  getImpactCandidates,
  type SystemMapProjection,
  type SystemMapNode,
  type SystemMapRelationship,
  type SystemMapGroup,
  type SystemMapMetadata,
  type SystemDimension,
  type SystemNodeContext,
  type TraversalOptions,
  type NeighborResult,
  type ImpactCandidate,
  type ImpactReason,
  type ImpactCandidatesResult,
} from './core/system-map.js'
export {
  loadSystemTopology,
  validateSystemTopology,
  buildTopologyEnrichmentHandoff,
  validateTopologyProposal,
  applyTopologyProposal,
  topologyRevision,
  TopologyWriteError,
  TOPOLOGY_FILE,
  type SystemEntity,
  type TechnicalRelationship,
  type SystemTopology,
  type TopologyFinding,
  type TopologyEnrichmentHandoff,
  type TopologyValidation,
  type TopologyApplyResult,
} from './core/system-topology.js'
export {
  listIntegrations,
  getIntegration,
  getIntegrationSecretStatus,
  getAvailableIntegrationTypes,
  createIntegration,
  updateIntegration,
  deleteIntegration,
  enableIntegration,
  disableIntegration,
  setIntegrationSecret,
  removeIntegrationSecret,
  verifyIntegration,
  listExternalWorkItems,
  getExternalWorkItem,
  findLinkedWorkItem,
  previewImport,
  importExternalWorkItem,
  discoverExternalWorkItems,
  getIntegrationFilters,
  updateIntegrationFilters,
  integrationRegistry,
  IntegrationServiceError,
  INTEGRATIONS_FILE,
  type IntegrationSummary,
  type AdapterTypeInfo,
  type UpdateIntegrationInput,
  type VerifyResult,
  type ImportPreviewResult,
  type ImportResult,
  type LinkedWorkItem,
  type DiscoveryResult,
  type DiscoveryIntegrationResult,
  type DiscoveryItemImportState,
  type EnrichedExternalWorkItem,
  type ImportIndex,
  buildImportIndex,
} from './services/integrations.js'
export {
  IntegrationError,
  validateConfigAgainstSchema,
  type IntegrationErrorCode,
  type ExternalWorkItem,
  type ExternalWorkItemPage,
  type ExternalWorkItemFilters,
  type FilterCapabilities,
  type ImportPreview,
  type IntegrationStatus,
  type IntegrationCapabilities,
  type IntegrationAdapterMetadata,
  type IntegrationInput,
  type ConfigFieldSchema,
  type ConnectionResult,
  type SchemaValidationFinding,
} from '../../integrations/src/index.js'
export { exists, readFile, join, cwd } from './utils/fs.js'
