import type { KaddoModule } from './types.js'

// Optional global knowledge artifacts (VS-017). These are NOT created during `kaddo init`
// — they are installed on demand so knowledge stays progressive. Each ships a starter
// template the corresponding operational agent can fill in via your LLM.

const standardsTemplate = [
  '# Standards',
  '',
  '> Starter template. Refine it with the Kaddo `standards-agent` in your LLM.',
  '> Keep it lightweight — a handful of high-value rules beats a long policy.',
  '',
  '## Coding standards',
  '',
  '- TODO: language/style conventions aligned with the detected stack.',
  '',
  '## Documentation standards',
  '',
  '- TODO: what must be documented, and where (artifacts near the code).',
  '',
  '## Testing expectations',
  '',
  '- TODO: minimum testing expectations per change type.',
  '',
  '## PR checklist',
  '',
  '- [ ] Linked to the right Work Item.',
  '- [ ] Knowledge updated or intentionally left unchanged.',
  '- [ ] Tests added/updated where it matters.',
  '',
].join('\n')

const securityTemplate = [
  '# Security Considerations',
  '',
  '> Starter template. Refine it with the Kaddo `security-agent` in your LLM.',
  '> Kaddo does **not** perform security scanning — this documents concerns for humans.',
  '',
  '## Authentication & authorization',
  '',
  '- TODO',
  '',
  '## Data sensitivity',
  '',
  '- TODO',
  '',
  '## Secrets handling',
  '',
  '- TODO',
  '',
  '## Dependency risks',
  '',
  '- TODO',
  '',
  '## Deployment risks',
  '',
  '- TODO',
  '',
  '## Open questions',
  '',
  '- TODO',
  '',
].join('\n')

const stackTemplate = [
  '# Stack',
  '',
  '> Starter template. Refine it with the Kaddo `stack-agent` in your LLM.',
  '',
  '## Languages',
  '',
  '- TODO',
  '',
  '## Frameworks',
  '',
  '- TODO',
  '',
  '## Data',
  '',
  '- TODO',
  '',
  '## Infrastructure',
  '',
  '- TODO',
  '',
  '## Tooling',
  '',
  '- TODO',
  '',
  '## Unknowns / needs confirmation',
  '',
  '- TODO',
  '',
].join('\n')

const gitStrategyTemplate = [
  '# Git Strategy',
  '',
  '> Starter template. Refine it with the Kaddo `git-strategy-agent` in your LLM.',
  '> Kaddo recommends a default and does **not** enforce it in CI.',
  '',
  '## Default strategy',
  '',
  'GitHub Flow + Conventional Commits + SemVer.',
  '',
  '## Branch naming',
  '',
  '```txt',
  'feature/<work-item-id>-<slug>',
  'bugfix/<work-item-id>-<slug>',
  'hotfix/<work-item-id>-<slug>',
  'spike/<work-item-id>-<slug>',
  'chore/<work-item-id>-<slug>',
  '```',
  '',
  '## Commit convention',
  '',
  '```txt',
  'feat(scope): message',
  'fix(scope): message',
  'docs(scope): message',
  'chore(scope): message',
  'refactor(scope): message',
  'test(scope): message',
  '```',
  '',
  '## Tag strategy',
  '',
  '```txt',
  'vMAJOR.MINOR.PATCH',
  '```',
  '',
  '## Release notes',
  '',
  'Sourced from Kaddo Work Items + Conventional Commits.',
  '',
  '## Customization',
  '',
  'Edit `.kaddo/git.yml` to switch strategy: `github-flow`, `gitflow`, `trunk-based` or',
  '`custom`.',
  '',
].join('\n')

const gitYml = [
  'strategy: github-flow',
  'branchNaming:',
  '  pattern: "{type}/{workItemId}-{slug}"',
  'commits:',
  '  convention: conventional-commits',
  '  requireWorkItemReference: true',
  'tags:',
  '  strategy: semver',
  '  pattern: "v{version}"',
  'release:',
  '  notesFrom:',
  '    - work-items',
  '    - commits',
  '',
].join('\n')

export const standardsModule: KaddoModule = {
  name: 'standards',
  description: 'Global standards starter — lightweight coding, docs and testing conventions',
  configKey: 'module_standards',
  dirs: ['architecture'],
  files: [{ path: 'architecture/standards.md', content: standardsTemplate }],
  workItemTypes: [],
}

export const securityModule: KaddoModule = {
  name: 'security',
  description: 'Global security starter — document security considerations (no scanning)',
  configKey: 'module_security',
  dirs: ['architecture'],
  files: [{ path: 'architecture/security.md', content: securityTemplate }],
  workItemTypes: [],
}

export const stackModule: KaddoModule = {
  name: 'stack',
  description: 'Global stack starter — document technologies and stack decisions',
  configKey: 'module_stack',
  dirs: ['architecture'],
  files: [{ path: 'architecture/stack.md', content: stackTemplate }],
  workItemTypes: [],
}

export const gitStrategyModule: KaddoModule = {
  name: 'git-strategy',
  description: 'Git strategy starter — default GitHub Flow + Conventional Commits + SemVer',
  configKey: 'module_git_strategy',
  dirs: ['architecture'],
  files: [
    { path: 'architecture/git-strategy.md', content: gitStrategyTemplate },
    { path: '.kaddo/git.yml', content: gitYml },
  ],
  workItemTypes: [],
}
